Repository cncf/toc, pull requests merged in 2020-07, with the labels that each got.

#330 Donate Contour to CNCF
  proposals/contour.adoc
Labels: incubation, new project, sig-network

#303 Request to present the Operator Framework to the TOC as an incubating project
  proposals/operator-framework.md
Labels: incubation, new project, reviewed-by-sig, sig-app-delivery

#376 Serverless Workflow Specification Sandbox Proposal
  proposals/serverlessworkflow.md
Labels: new project, sandbox, sig-app-delivery

#367 add chaos mesh proposal for sandbox entry
  proposals/chaos-mesh.md
Labels: sandbox, sig-network

#433 OpenEBS 2020 Annual Review
  reviews/2020-openebs-annual.md
Labels: annual review

#440 2020 KubeEdge Annual Review
  reviews/2020-kubeedge-annual.md
Labels: annual review
