Repository cncf/toc, pull requests merged in 2024-05, with the labels that each got.

#1309 Remove projects.csv as it is replaced by landscape2
  docs/PROJECTS.csv
Labels: process-documentation

#1305 Update TAG app delivery personell
  tags/cncf-tags.md
  tags/emeritus_leaders.md
  tags/tag-charters/app-delivery.md
Labels: tag-app-delivery, process-documentation

#1324 Add README and charter templates
  tags/resources/tag-formation-templates/README.md
  tags/resources/tag-formation-templates/template-tag-charter.md
  tags/resources/tag-formation-templates/template-tag-readme.md
Labels: process-documentation

#1327 Add landscape instructions linked to the project on-boarding template
  .github/ISSUE_TEMPLATE/project-onboarding.md
Labels: process-documentation

#1325 Add TAG Leadership voting template
  .github/ISSUE_TEMPLATE/tag-leadership-nomination.yaml
Labels: process-documentation

#1330 Add drop down options for TAG and position
  .github/ISSUE_TEMPLATE/tag-leadership-nomination.yaml
Labels: process-documentation

#1331 Update the tag yaml file drop down function
  .github/ISSUE_TEMPLATE/tag-leadership-nomination.yaml
Labels: process-documentation

#1339 Add Working Group Leadership nomination process
  tags/README.md
Labels: process-documentation

#1343 Correct heading level md for WG Leads heading
  tags/README.md
Labels: process-documentation

#1341 Update TAG App Delivery and TAG Network in cncf-tags.md
  tags/cncf-tags.md
Labels: tag-app-delivery, tag-network
